<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net9.0-android;net9.0-ios</TargetFrameworks>
		<!-- Uncomment to also build the tizen app. You will need to install tizen by following this: https://github.com/Samsung/Tizen.NET -->
		<!-- <TargetFrameworks>$(TargetFrameworks);net9.0-tizen</TargetFrameworks> -->

		<!-- Note for MacCatalyst:
		The default runtime is maccatalyst-x64, except in Release config, in which case the default is maccatalyst-x64;maccatalyst-arm64.
		When specifying both architectures, use the plural <RuntimeIdentifiers> instead of the singular <RuntimeIdentifier>.
		The Mac App Store will NOT accept apps with ONLY maccatalyst-arm64 indicated;
		either BOTH runtimes must be indicated or ONLY macatalyst-x64. -->
		<!-- For example: <RuntimeIdentifiers>maccatalyst-x64;maccatalyst-arm64</RuntimeIdentifiers> -->

		<OutputType>Exe</OutputType>
		<RootNamespace>VMedic</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<!-- Display name -->
		<ApplicationTitle>VMedic</ApplicationTitle>
	
		<!-- App Identifier -->
		<ApplicationId>com.softwaremobilesolutions.vmedic</ApplicationId>

		<!-- Versions -->
		<!-- Published Versions === Android 0 (0.0.0) || iOS 0 (0.0.0) -->
		<!-- VMEDIC 1 1 2.0.0 -->
		<ApplicationDisplayVersion>2.0.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<!-- To develop, package, and publish an app to the Microsoft Store, see: https://aka.ms/MauiTemplateUnpackaged -->
		<WindowsPackageType>None</WindowsPackageType>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">6.5</SupportedOSPlatformVersion>
		<AndroidSigningKeyStore />
	</PropertyGroup>

	<PropertyGroup Condition="'$(TargetFramework)' == 'net9.0-android'">
		<RuntimeIdentifiers>android-arm64;android-arm;android-x64</RuntimeIdentifiers>
	</PropertyGroup>

	<PropertyGroup Condition="$(TargetFramework.Contains('-windows'))">
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
	</PropertyGroup>

	<PropertyGroup Condition="'$(TargetFramework)' == 'net9.0-ios'">
		<ApplicationVersion>1</ApplicationVersion> <!--VERSION DE COMPILACION DE IOS-->
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<PropertyGroup Condition="'$(TargetFramework)' == 'net9.0-android'">
		<ApplicationVersion>2</ApplicationVersion> <!--VERSION DE COMPILACION DE ANDROID-->
		<usemaui>true</usemaui>
		<targetandroidversion>35</targetandroidversion>
		<targetsdkversion>35</targetsdkversion>
		<supportedosplatformversion>23</supportedosplatformversion>
	</PropertyGroup>

	<!--Publicar en IOS-->
	<!--dotnet publish -f:net9.0-ios -c:Release /p:RuntimeIdentifier=ios-arm64 /p:PlatformTarget=arm64 /p:CodesignKey="Apple Distribution: Guillermo Amaya (WP4G78EVWV)" /p:CodesingProvision=VMedicIOS /p:ServerAddress=192.168.1.145 /p:ServerUser=softwaremobilesolutions /p:TcpPort=58181 /p:ArchiveOnBuild=true /p:_DotNetRootRemoteDirectory='/Users/softwaremobilesolutions/Library/Caches/maui/PairToMac/SDKs/dotnet/' /p:EnableAssemblyILStripping=false /p:ServerPassword=Coreuser2025.-->
	<!--Cambiar el numero de application Version o número de compilación-->
	<PropertyGroup Condition="$(TargetFramework.Contains('-ios')) and '$(Configuration)' == 'Release'">
		<RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
		<PlatformTarget>arm64</PlatformTarget>
		<EnablePushNotifications>true</EnablePushNotifications>
		<CodesignKey>Apple Distribution: Guillermo Amaya (WP4G78EVWV)</CodesignKey>
		<CodesingProvision>VMedicIOS</CodesingProvision>
		<ServerAddress>192.168.1.145</ServerAddress>
		<ServerUser>softwaremobilesolutions</ServerUser>
		<TcpPort>58181</TcpPort>
		<ArchiveOnBuild>true</ArchiveOnBuild>
		<_DotNetRootRemoteDirectory>/Users/softwaremobilesolutions/Library/Caches/maui/PairToMac/SDKs/dotnet/</_DotNetRootRemoteDirectory>
		<EnableAssemblyILStripping>false</EnableAssemblyILStripping>
	</PropertyGroup>

	<!--Publicar en Android-->
	<!--dotnet publish -f:net9.0-android -c Release /p:RuntimeIdentifier=android-arm64 /p:PlatformTarget=arm64 /p:SignAndroidPackage=true /p:AndroidKeyStore=true /p:AndroidSigningKeyAlias=vmedic /p:AndroidSigningKeyPass=123456789 /p:AndroidSigningStorePass=123456789 /p:AndroidSigningKeyStore="C:\Users\Desarrollador\AppData\Local\Xamarin\Mono for Android\Keystore\vmedic\vmedic.keystore"-->
	<!--D:\Shared\apps\BackUpProyectosMoviles\VisualStudio\Vmedic\Vmedic\bin\Release\net9.0-android\publish-->
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net9.0-android|AnyCPU'">
		<RuntimeIdentifiers>android-arm64</RuntimeIdentifiers>
		<PlatformTarget>arm64</PlatformTarget>
		<AndroidUseAapt2>True</AndroidUseAapt2>
		<AndroidCreatePackagePerAbi>False</AndroidCreatePackagePerAbi>
		<!--<AndroidPackageFormat>apk</AndroidPackageFormat>-->
		<!--<AndroidPackageFormat>aab</AndroidPackageFormat>-->
		<AndroidPackageFormat>aab</AndroidPackageFormat>
		<AndroidKeyStore>true</AndroidKeyStore>
		<AndroidSigningKeyAlias></AndroidSigningKeyAlias>
		<AndroidSigningKeyPass></AndroidSigningKeyPass>
		<AndroidSigningStorePass></AndroidSigningStorePass>
		<AndroidSigningKeyStore>C:\Users\Desarrollador\AppData\Local\Xamarin\Mono for Android\Keystore\vmedic\vmedic.keystore</AndroidSigningKeyStore>
	</PropertyGroup>

	<ItemGroup>
		<!-- App Icon -->
		<MauiIcon Include="Resources\AppIcon\ic_launcher.png" />

		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />
		<MauiImage Update="Resources\Images\dotnet_bot.png" Resize="True" BaseSize="300,185" />
		
		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />

		<MauiSplashScreen Include="Resources\Splash\ic_launcher_icon.png" Color="#FFF" />
	</ItemGroup>

	<ItemGroup>
	  <MauiImage Remove="Resources\Images\medic.png" />
	  <MauiImage Remove="Resources\Images\medic_part1.png" />
	  <MauiImage Remove="Resources\Images\medic_part2.png" />
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Include="Resources\Images\medic.png" />
	  <EmbeddedResource Include="Resources\Images\medic_part1.png" />
	  <EmbeddedResource Include="Resources\Images\medic_part2.png" />
	</ItemGroup>
		
	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Maui" Version="12.2.0" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="9.0.120" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="9.0.10" />
		<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="9.0.120" />
		<PackageReference Include="Microsoft.Maui.Controls.Maps" Version="9.0.120" />
		<PackageReference Include="Microsoft.Maui.Essentials" Version="9.0.120" />
		<PackageReference Include="Microsoft.Maui.Graphics" Version="9.0.120" />
		<PackageReference Include="Mopups" Version="1.3.4" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="PropertyChanged.Fody" Version="4.1.0" />
		<PackageReference Include="SkiaSharp" Version="3.119.1" />
		<PackageReference Include="sqlite-net-pcl" Version="1.9.172" />
		<PackageReference Include="SQLiteNetExtensions" Version="2.1.0" />
		<PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.2" />
		<PackageReference Include="Syncfusion.Licensing" Version="31.2.4" />
		<PackageReference Include="Syncfusion.Maui.Calendar" Version="31.2.4" />
		<PackageReference Include="Syncfusion.Maui.Core" Version="31.2.4" />
		<PackageReference Include="Syncfusion.Maui.Gauges" Version="31.2.4" />
		<PackageReference Include="Syncfusion.Maui.Inputs" Version="31.2.4" />
		<PackageReference Include="Syncfusion.Maui.Scheduler" Version="31.2.4" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="MVVM\Models\SKObjects\" />
	</ItemGroup>

	<ItemGroup>
	  <MauiXaml Update="MVVM\Views\ConfiguracionView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="MVVM\Views\Inventario\InventarioView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="MVVM\Views\LoginView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="MVVM\Views\Menus\MenuMedicos.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="MVVM\Views\Médicos\EditarMedicoView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="MVVM\Views\Médicos\EnviarMedicosPendientesView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="MVVM\Views\Médicos\InformacionMedicoView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="MVVM\Views\Médicos\MedicosPendientesView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="MVVM\Views\Médicos\MedicosView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="MVVM\Views\Médicos\NuevoMedicoView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="MVVM\Views\Planificacion\NuevaVisitaPlanificacionView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="MVVM\Views\Planificacion\PlanificacionView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="MVVM\Views\Visitas\CapturarFirmaView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="MVVM\Views\Visitas\EvaluacionesView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="MVVM\Views\Visitas\NuevaEvaluacionView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="MVVM\Views\Visitas\PromocionalesView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="MVVM\Views\Visitas\VisitasPendientesView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="MVVM\Views\Visitas\VisitasView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	</ItemGroup>

</Project>
